# Generated by Django 3.2.9 on 2020-12-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=' آدرس گيت هاب'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر شما براي نمايش در سايت'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=' آدرس اینستاگرام'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تخصص'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=' آدرس لينكدين'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=' آدرس تلگرام'),
        ),
    ]
