# Generated by Django 3.2.9 on 2020-12-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('p', 'منتشر شده'), ('d', 'پیش نویس'), ('i', ' در حال بررسی'), ('b', ' برگشت داده شده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
