# Generated by Django 3.2.9 on 2020-12-11 23:02

from django.db import migrations, models
import settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان سایت')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل')),
                ('copy_right', models.TextField(blank=True, null=True, verbose_name='متن کپی رایت')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to=settings.models.upload_image_path, verbose_name='تصویر لوگو')),
                ('instagram', models.CharField(blank=True, max_length=150, null=True, verbose_name=' آدرس اینستاگرام')),
                ('linkedin', models.CharField(blank=True, max_length=150, null=True, verbose_name=' آدرس لينكدين')),
                ('github', models.CharField(blank=True, max_length=150, null=True, verbose_name=' آدرس گيت هاب')),
                ('telegram', models.CharField(blank=True, max_length=150, null=True, verbose_name=' آدرس تلگرام')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'مدیریت تنظیمات',
            },
        ),
    ]
